'''
QUESTION: What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

ANSWER: 4782

EXPLANATION: The Fibonacci sequence is generated by adding the previous two terms. The first two terms are 1 and 1. The sequence is generated by the following formula:
Fn = Fn-1 + Fn-2
'''
a = 1
b = 1
i = 2
while True:
    i += 1
    a, b = b, a + b
    if len(str(b)) == 1000:
        break
print(i)
